### ISSUE TITLE
linux下使用问题

### ISSUE THREAD

**Issue by d0ng1ee** [SunskyF/StructCompletion-python#4]
作者您好，我希望在linux环境下使用您的代码，请问您能把编译生成vpdetection.exe文件的源代码公布吗，谢谢！

**Comment by SunskyF** [comment]
vpdetection.exe是从官方版本中拿来的，我猜是使用的这里的
https://github.com/simbaforrest/vpdetection

**Comment by d0ng1ee** [comment]
好的，多谢！

**Comment by Matt-V50** [comment]
> 好的，多谢！

确定是这个吗？@donglee-afar
